<?php

namespace FaviziBundle\Repository;

/**
 * ItemPublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPublicRepository extends \Doctrine\ORM\EntityRepository
{
}
