<?php

namespace FaviziBundle\Repository;

/**
 * ItemPriveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPriveRepository extends \Doctrine\ORM\EntityRepository
{
}
