<?php

namespace FaviziBundle\Repository;

/**
 * LiaisonCUIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiaisonCUIRepository extends \Doctrine\ORM\EntityRepository
{
}
